# Generated by Django 5.1.3 on 2024-12-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0011_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
    ]
