# Generated by Django 4.2.16 on 2024-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usefulinks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefullink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='link_images/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
    ]
