# Generated by Django 5.1.3 on 2024-12-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-id']},
        ),
    ]
