# Generated by Django 5.1.3 on 2024-12-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creater',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
