# Generated by Django 5.1.3 on 2024-12-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_post_comment_like_dislike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('category_create', 'Can create category')]},
        ),
    ]
