# Generated by Django 5.1.3 on 2024-11-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': [('can_publish', 'Can Publish Articles')]},
        ),
    ]
