# Generated by Django 5.1.3 on 2024-12-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_pages', '0005_event'),
        ('default_pages', '0005_notification'),
    ]

    operations = [
    ]
